name: Cron

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    name: Cron
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: yarn install

      - name: Run
        run: yarn index