name: Test runner

on: workflow_dispatch

jobs:
  build:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: push

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies 
        working-directory: ./tools
        run: yarn install

      - name: Run 
        working-directory: ./tools
        run: yarn files

      - name: Commit files
        env:
          SRC_FOLDER_PATH: 'data'
          SOURCE_BRANCH: 'push'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout $SOURCE_BRANCH                     # checkout the source branch (same as checkout ref in step 1)
          git add --all
          git commit -m "Automated commit" -a

      - name: Merge files
        env:
          SRC_FOLDER_PATH: 'data'
          TARGET_BRANCH: 'main'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)          # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                                       # fetch branches
          git checkout $TARGET_BRANCH                     # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files        # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "Automated merge"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH                  # push to remote branch