name: Test runner

on: workflow_dispatch

jobs:
  build:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies on sub
        working-directory: ./tools
        run: yarn install

      - name: Run on sub
        working-directory: ./tools
        run: yarn files

      - name: Create file on root
        run: date +%s > ./data/report.txt
        working-directory: ./

      - name: Re-Run on sub 
        working-directory: ./tools
        run: yarn files

